# Copyright (c) 2017, Juniper Networks, Inc.
# # All rights reserved.
#
version: "3"

services:

  vmx1:
    image: juniper/openjnpr-container-vmx:bionic
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx1
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-18.2R1.9.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=vmx1.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-a:
      net-b:
      net-c:

  vmx2:
    image: juniper/openjnpr-container-vmx:trusty
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx2
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-18.1R1.9.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=vmx2.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-a:
      net-b:
      net-c:

networks:
  mgmt:
  net-a:
  net-b:
  net-c:
