# Copyright (c) 2017, Juniper Networks, Inc.
# # All rights reserved.
#
version: "3"

services:

  vmx1:
    image: juniper/openjnpr-container-vmx:bionic
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx1
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-18.2R1.9.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=regression/vmx1.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-a:
      net-b:
      net-c:

  vmx2:
    image: juniper/openjnpr-container-vmx:trusty
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx2
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-18.1R1.9.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=regression/vmx2.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-a:
      net-b:
      net-c:

  vmx3:
    image: juniper/openjnpr-container-vmx:trusty
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx3
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-17.4R1.16.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=regression/vmx3.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-a:
      net-b:
      net-c:

  vmx4:
    image: juniper/openjnpr-container-vmx:trusty
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx4
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-17.3R2.10.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=regression/vmx4.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-a:
      net-b:
      net-c:

  vmx5:
    image: juniper/openjnpr-container-vmx:trusty
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx5
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-17.3R1.10.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=regression/vmx5.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-a:
      net-b:
      net-c:

  vmx6:
    image: juniper/openjnpr-container-vmx:trusty
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx6
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-18.1R2.5.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=regression/vmx6.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-a:
      net-b:
      net-c:

  vmx7:
    image: juniper/openjnpr-container-vmx:bionic
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - ID=vmx6
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-18.3R1.9.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=regression/vmx7.conf
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mgmt:
      net-a:
      net-b:
      net-c:

networks:
  mgmt:
  net-a:
  net-b:
  net-c:
